[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
holderscan_dca = "2k7JFjY617MMCsshPMpRkYxR4Cx1gALPeFgNpfvCg4G5"

[programs.devnet]
holderscan_dca = "2k7JFjY617MMCsshPMpRkYxR4Cx1gALPeFgNpfvCg4G5"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
